/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateClassroomArgs } from "./CreateClassroomArgs";
import { UpdateClassroomArgs } from "./UpdateClassroomArgs";
import { DeleteClassroomArgs } from "./DeleteClassroomArgs";
import { ClassroomFindManyArgs } from "./ClassroomFindManyArgs";
import { ClassroomFindUniqueArgs } from "./ClassroomFindUniqueArgs";
import { Classroom } from "./Classroom";
import { ClassroomService } from "../classroom.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Classroom)
export class ClassroomResolverBase {
  constructor(
    protected readonly service: ClassroomService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Classroom",
    action: "read",
    possession: "any",
  })
  async _classroomsMeta(
    @graphql.Args() args: ClassroomFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Classroom])
  @nestAccessControl.UseRoles({
    resource: "Classroom",
    action: "read",
    possession: "any",
  })
  async classrooms(
    @graphql.Args() args: ClassroomFindManyArgs
  ): Promise<Classroom[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Classroom, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Classroom",
    action: "read",
    possession: "own",
  })
  async classroom(
    @graphql.Args() args: ClassroomFindUniqueArgs
  ): Promise<Classroom | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Classroom)
  @nestAccessControl.UseRoles({
    resource: "Classroom",
    action: "create",
    possession: "any",
  })
  async createClassroom(
    @graphql.Args() args: CreateClassroomArgs
  ): Promise<Classroom> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Classroom)
  @nestAccessControl.UseRoles({
    resource: "Classroom",
    action: "update",
    possession: "any",
  })
  async updateClassroom(
    @graphql.Args() args: UpdateClassroomArgs
  ): Promise<Classroom | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Classroom)
  @nestAccessControl.UseRoles({
    resource: "Classroom",
    action: "delete",
    possession: "any",
  })
  async deleteClassroom(
    @graphql.Args() args: DeleteClassroomArgs
  ): Promise<Classroom | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
